

const paises = [
  { id: 1, nombre: 'Australia' },
  { id: 2, nombre: 'Austria' },
  { id: 3, nombre: 'Azerbaiyán' },
  { id: 4, nombre: 'Anguilla' },
  { id: 5, nombre: 'Argentina' },
  { id: 6, nombre: 'Armenia' },
  { id: 7, nombre: 'Bielorrusia' },
  { id: 8, nombre: 'Belice' },
  { id: 9, nombre: 'Bélgica' },
  { id: 10, nombre: 'Bermudas' },
  { id: 11, nombre: 'Bulgaria' },
  { id: 12, nombre: 'Brasil' },
  { id: 13, nombre: 'Reino Unido' },
  { id: 14, nombre: 'Hungría' },
  { id: 15, nombre: 'Vietnam' },
  { id: 16, nombre: 'Haiti' },
  { id: 17, nombre: 'Guadalupe' },
  { id: 18, nombre: 'Alemania' },
  { id: 19, nombre: 'Países Bajos, Holanda' },
  { id: 20, nombre: 'Grecia' },
  { id: 21, nombre: 'Georgia' },
  { id: 22, nombre: 'Dinamarca' },
  { id: 23, nombre: 'Egipto' },
  { id: 24, nombre: 'Israel' },
  { id: 25, nombre: 'India' },
  { id: 26, nombre: 'Irán' },
  { id: 27, nombre: 'Irlanda' },
  { id: 28, nombre: 'España' },
  { id: 29, nombre: 'Italia' },
  { id: 30, nombre: 'Kazajstán' },
  { id: 31, nombre: 'Camerún' },
  { id: 32, nombre: 'Canadá' },
  { id: 33, nombre: 'Chipre' },
  { id: 34, nombre: 'Kirguistán' },
  { id: 35, nombre: 'China' },
  { id: 36, nombre: 'Costa Rica' },
  { id: 37, nombre: 'Kuwait' },
  { id: 38, nombre: 'Letonia' },
  { id: 39, nombre: 'Libia' },
  { id: 40, nombre: 'Lituania' },
  { id: 41, nombre: 'Luxemburgo' },
  { id: 42, nombre: 'México' },
  { id: 43, nombre: 'Moldavia' },
  { id: 44, nombre: 'Mónaco' },
  { id: 45, nombre: 'Nueva Zelanda' },
  { id: 46, nombre: 'Noruega' },
  { id: 47, nombre: 'Polonia' },
  { id: 48, nombre: 'Portugal' },
  { id: 49, nombre: 'Reunión' },
  { id: 50, nombre: 'Rusia' },
  { id: 51, nombre: 'El Salvador' },
  { id: 52, nombre: 'Eslovaquia' },
  { id: 53, nombre: 'Eslovenia' },
  { id: 54, nombre: 'Surinam' },
  { id: 55, nombre: 'Estados Unidos' },
  { id: 56, nombre: 'Tadjikistan' },
  { id: 57, nombre: 'Turkmenistan' },
  { id: 58, nombre: 'Islas Turcas y Caicos' },
  { id: 59, nombre: 'Turquía' },
  { id: 60, nombre: 'Uganda' },
  { id: 61, nombre: 'Uzbekistán' },
  { id: 62, nombre: 'Ucrania' },
  { id: 63, nombre: 'Finlandia' },
  { id: 64, nombre: 'Francia' },
  { id: 65, nombre: 'República Checa' },
  { id: 66, nombre: 'Suiza' },
  { id: 67, nombre: 'Suecia' },
  { id: 68, nombre: 'Estonia' },
  { id: 69, nombre: 'Corea del Sur' },
  { id: 70, nombre: 'Japón' },
  { id: 71, nombre: 'Croacia' },
  { id: 72, nombre: 'Rumanía' },
  { id: 73, nombre: 'Hong Kong' },
  { id: 74, nombre: 'Indonesia' },
  { id: 75, nombre: 'Jordania' },
  { id: 76, nombre: 'Malasia' },
  { id: 77, nombre: 'Singapur' },
  { id: 78, nombre: 'Taiwan' },
  { id: 79, nombre: 'Bosnia y Herzegovina' },
  { id: 80, nombre: 'Bahamas' },
  { id: 81, nombre: 'Chile' },
  { id: 82, nombre: 'Colombia' },
  { id: 83, nombre: 'Islandia' },
  { id: 84, nombre: 'Corea del Norte' },
  { id: 85, nombre: 'Macedonia' },
  { id: 86, nombre: 'Malta' },
  { id: 87, nombre: 'Pakistán' },
  { id: 88, nombre: 'Papúa-Nueva Guinea' },
  { id: 89, nombre: 'Perú' },
  { id: 90, nombre: 'Filipinas' },
  { id: 91, nombre: 'Arabia Saudita' },
  { id: 92, nombre: 'Tailandia' },
  { id: 93, nombre: 'Emiratos árabes Unidos' },
  { id: 94, nombre: 'Groenlandia' },
  { id: 95, nombre: 'Venezuela' },
  { id: 96, nombre: 'Zimbabwe' },
  { id: 97, nombre: 'Kenia' },
  { id: 98, nombre: 'Algeria' },
  { id: 99, nombre: 'Líbano' },
  { id: 100, nombre: 'Botsuana' },
  { id: 101, nombre: 'Tanzania' },
  { id: 102, nombre: 'Namibia' },
  { id: 103, nombre: 'Ecuador' },
  { id: 104, nombre: 'Marruecos' },
  { id: 105, nombre: 'Ghana' },
  { id: 106, nombre: 'Siria' },
  { id: 107, nombre: 'Nepal' },
  { id: 108, nombre: 'Mauritania' },
  { id: 109, nombre: 'Seychelles' },
  { id: 110, nombre: 'Paraguay' },
  { id: 111, nombre: 'Uruguay' },
  { id: 112, nombre: 'Congo (Brazzaville)' },
  { id: 113, nombre: 'Cuba' },
  { id: 114, nombre: 'Albania' },
  { id: 115, nombre: 'Nigeria' },
  { id: 116, nombre: 'Zambia' },
  { id: 117, nombre: 'Mozambique' },
  { id: 119, nombre: 'Angola' },
  { id: 120, nombre: 'Sri Lanka' },
  { id: 121, nombre: 'Etiopía' },
  { id: 122, nombre: 'Túnez' },
  { id: 123, nombre: 'Bolivia' },
  { id: 124, nombre: 'Panamá' },
  { id: 125, nombre: 'Malawi' },
  { id: 126, nombre: 'Liechtenstein' },
  { id: 127, nombre: 'Bahrein' },
  { id: 128, nombre: 'Barbados' },
  { id: 130, nombre: 'Chad' },
  { id: 131, nombre: 'Man, Isla de' },
  { id: 132, nombre: 'Jamaica' },
  { id: 133, nombre: 'Malí' },
  { id: 134, nombre: 'Madagascar' },
  { id: 135, nombre: 'Senegal' },
  { id: 136, nombre: 'Togo' },
  { id: 137, nombre: 'Honduras' },
  { id: 138, nombre: 'República Dominicana' },
  { id: 139, nombre: 'Mongolia' },
  { id: 140, nombre: 'Puerto Rico' }
];

module.exports = paises;
